#FilterInfo:
FilterDir: "/home/binsun/microglia_MACH/microglia_MACH/filter_images/"
FilterNames:
  NormalFilters: ['ram','rod','hyp','amoe','dys','newrod']  # normal MACH filter constructed from cropped cells, added a newrodfiler (120x120 size)
  PenaltyFilters: ['rodp','rrodp','ramoep','newrodp'] 
    # "rodp" : penalty filter for rod filter constructed from rampfiled filter by masking out the rod part
    # "rrodp" : penalty filter for rod filter by reversing the rod filter [np.max(rod) - rod]
    # "ramoep": similar to rrodp, reversing the amoe filter

  PartialFilters: ['ramp','hypp'] 
    # "ramp" : process only filter of ramified filter
    # "hypp" : process only filter of hypertrophic filter


#TODO: implement the FilterOrder 2
FilterOrder: 1
# 1: pick up rod --> pick up ramified/hypertrophic --> pick up amoeboid/dystrophic
# 2: pick up ramified/hypertrophic --> pick up rod --> pick up amoebioid/dystrophic

PenaltyFilterOption: 3 # 1--> use rodp, 2--> use rrodp, 3--> use the newrod/newrodp
RotationAngles: [15,30,45,60,75,90,105,120,135,150,165,180] # angles for the rotation of the rod and the penalty filter

# thresholding values
rodSNR: [2.0,0.27,0.76] # for rodp, rrodp and newrod, respectively.

rampThres: 0.22
hyppThres: 0.18

amoeThres: 0.33
areaThres: 210



# ==== This part is for the test image only, do not change the following ====

#Parameters used for testing the filtering protocol
InputImage: "./TestImages/newSample.png" #the input image
TrueImage: "./TestImages/Sample_annotate.png" #the annotated truth image, for validation only. Set as "None" if it is normal run
